name: Test API

on:
  push:
    branches:
      - main

env:
  TEST: 1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn pytest fastapi httpx sqlalchemy pyjwt pyyaml mysql-connector-python python-multipart pymysql cryptography
        sudo service mysql start        
        echo "UPDATE mysql.user SET authentication_string=PASSWORD('Passw0rd+'), password_expired='N' WHERE User='root' AND Host='localhost';" | sudo mysql --skip-grant-tables
        sudo service mysql restart

    - name: Run pytest
      run: |
        cd Tests
        pytest