name: Test API

on:
  push:
    branches:
      - main

env:
  TEST: 1

jobs:
  test:
    runs-on: ubuntu-latest     
          
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11   
      
    - name: MySQL
      run: |
        sudo apt install mysql-server
        sudo service mysql start
        cd /var/run
        sudo cp -rp ./mysqld ./mysqld.bak
        sudo service mysql stop
        sudo mv ./mysqld.bak ./mysqld
        sudo mysqld_safe –skip-grant-tables –skip-networking &
        echo "UPDATE mysql.user SET authentication_string=null WHERE User='root';flush privileges;ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'Passw0rd+';flush privileges;" | mysql -u root
