name: Test API

on:
  push:
    branches:
      - main

env:
  TEST: 1

jobs:
  test:
    runs-on: ubuntu-latest     
          
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11   
      
    - name: MySQL
      run: |
        sudo apt install mysql-server
        sudo service mysql start
        ls /var/run/mysqld/
        sudo mysqld_safe --skip-grant-tables &
        sudo mysql --user=root mysql
