name: Test API

on:
  push:
    branches:
      - main

env:
  TEST: 1
  MYSQL_ROOT_PASSWORD: Passw0rd+

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest          
          
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Start MySQL container
      uses: docker://mysql:8.0
      with:
        args: --default-authentication-plugin=mysql_native_password         
      
    - name: Connect to MySQL
      run: |
        mysql -u root -p${{ env.MYSQL_ROOT_PASSWORD }}
