name: Tests workflow

on:
  pull_request:
    branches:
      - main

env:
  TEST: 1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.6

    - name: Install libraries
      run: |
        pip install -r .github/workflows/requirements.txt
        
    - name: Set MySQL
      run: |
        sudo service mysql start
        echo "ALTER USER 'root'@'localhost' IDENTIFIED BY '${{ secrets.NEW_MYSQL_PASSWORD }}';" | mysql -u root -p${{ secrets.OLD_MYSQL_PASSWORD }}
    
    - name: Run tests
      run: |
        cd Tests
        pytest
