name: Test API

on:
  push:
    branches:
      - main

env:
  TEST: 1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install MySQL
      run: |        
        sudo apt install mysql-server
        pwd
        ls
        sudo echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'MyNewPass';" >> /home/mysql-init
        ll /home/mysql-init
        cat /home/mysql-init
        chmod 777 /home/mysql-init
        ll /home/mysql-init
        mysqld --init-file=/home/mysql-init &
