name: Test API

on:
  push:
    branches:
      - main

env:
  TEST: 1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install MySQL
      run: |        
        sudo apt install mysql-server
        sudo echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'Passw0rd+';" >> /home/runner/work/mysql-init
        sudo mysqld --init-file=/home/runner/work/mysql-init &
        mysql -u root -pPassw0rd+
