name: Test API

on:
  push:
    branches:
      - main

env:
  TEST: 1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn pytest fastapi httpx sqlalchemy pyjwt pyyaml mysql-connector-python python-multipart pymysql cryptography
        sudo mysqld_safe --skip-grant-tables &
        cat /var/log/mysql/error.log               
        echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'Passw0rd+';" | mysql -u root
        sudo systemctl restart mysql

    - name: Run pytest
      run: |
        cd Tests
        pytest